In [5]:
import psycopg2

host = 'salt.db.elephantsql.com'
user = 'acnpuhxb'
database = 'acnpuhxb'
password = 'O2E1QUU8yL1d2PjrQ8XYCwwWI-vDMK3M'
pg_conn = psycopg2.connect(
    database=database, user=user, password=password, host=host)
pg_cur = pg_conn.cursor()


query = """
SELECT * FROM "public"."Titanic"
"""
pg_cur.execute(query)
pg_cur.fetchall()

[('Mr. Owen Harris Braund', 0, 3, 'male', 22.0, 1, 0, 7.25),
 ('Mrs. John Bradley (Florence Briggs Thayer) Cumings',
  1,
  1,
  'female',
  38.0,
  1,
  0,
  71.2833),
 ('Miss. Laina Heikkinen', 1, 3, 'female', 26.0, 0, 0, 7.925),
 ('Mrs. Jacques Heath (Lily May Peel) Futrelle',
  1,
  1,
  'female',
  35.0,
  1,
  0,
  53.1),
 ('Mr. William Henry Allen', 0, 3, 'male', 35.0, 0, 0, 8.05),
 ('Mr. James Moran', 0, 3, 'male', 27.0, 0, 0, 8.4583),
 ('Mr. Timothy J McCarthy', 0, 1, 'male', 54.0, 0, 0, 51.8625),
 ('Master. Gosta Leonard Palsson', 0, 3, 'male', 2.0, 3, 1, 21.075),
 ('Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson',
  1,
  3,
  'female',
  27.0,
  0,
  2,
  11.1333),
 ('Mrs. Nicholas (Adele Achem) Nasser', 1, 2, 'female', 14.0, 1, 0, 30.0708),
 ('Miss. Marguerite Rut Sandstrom', 1, 3, 'female', 4.0, 1, 1, 16.7),
 ('Miss. Elizabeth Bonnell', 1, 1, 'female', 58.0, 0, 0, 26.55),
 ('Mr. William Henry Saundercock', 0, 3, 'male', 20.0, 0, 0, 8.05),
 ('Mr. Anders Johan Andersson', 0, 3, 'male', 39.0, 1, 5, 31.275),
 ('Miss. Hulda Amanda Adolfina Vestrom', 0, 3, 'female', 14.0, 0, 0, 7.8542),
 ('Mrs. (Mary D Kingcome) Hewlett', 1, 2, 'female', 55.0, 0, 0, 16.0),
 ('Master. Eugene Rice', 0, 3, 'male', 2.0, 4, 1, 29.125),
 ('Mr. Charles Eugene Williams', 1, 2, 'male', 23.0, 0, 0, 13.0),
 ('Mrs. Julius (Emelia Maria Vandemoortele) Vander Planke',
  0,
  3,
  'female',
  31.0,
  1,
  0,
  18.0),
 ('Mrs. Fatima Masselmani', 1, 3, 'female', 22.0, 0, 0, 7.225),
 ('Mr. Joseph J Fynney', 0, 2, 'male', 35.0, 0, 0, 26.0),
 ('Mr. Lawrence Beesley', 1, 2, 'male', 34.0, 0, 0, 13.0),
 ('Miss. Anna McGowan', 1, 3, 'female', 15.0, 0, 0, 8.0292),
 ('Mr. William Thompson Sloper', 1, 1, 'male', 28.0, 0, 0, 35.5),
 ('Miss. Torborg Danira Palsson', 0, 3, 'female', 8.0, 3, 1, 21.075),
 ('Mrs. Carl Oscar (Selma Augusta Emilia Johansson) Asplund',
  1,
  3,
  'female',
  38.0,
  1,
  5,
  31.3875),
 ('Mr. Farred Chehab Emir', 0, 3, 'male', 26.0, 0, 0, 7.225),
 ('Mr. Charles Alexander Fortune', 0, 1, 'male', 19.0, 3, 2, 263.0),
 ("Miss. Ellen O'Dwyer", 1, 3, 'female', 24.0, 0, 0, 7.8792),
 ('Mr. Lalio Todoroff', 0, 3, 'male', 23.0, 0, 0, 7.8958),
 ('Don. Manuel E Uruchurtu', 0, 1, 'male', 40.0, 0, 0, 27.7208),
 ('Mrs. William Augustus (Marie Eugenie) Spencer',
  1,
  1,
  'female',
  48.0,
  1,
  0,
  146.5208),
 ('Miss. Mary Agatha Glynn', 1, 3, 'female', 18.0, 0, 0, 7.75),
 ('Mr. Edward H Wheadon', 0, 2, 'male', 66.0, 0, 0, 10.5),
 ('Mr. Edgar Joseph Meyer', 0, 1, 'male', 28.0, 1, 0, 82.1708),
 ('Mr. Alexander Oskar Holverson', 0, 1, 'male', 42.0, 1, 0, 52.0),
 ('Mr. Hanna Mamee', 1, 3, 'male', 18.0, 0, 0, 7.2292),
 ('Mr. Ernest Charles Cann', 0, 3, 'male', 21.0, 0, 0, 8.05),
 ('Miss. Augusta Maria Vander Planke', 0, 3, 'female', 18.0, 2, 0, 18.0),
 ('Miss. Jamila Nicola-Yarred', 1, 3, 'female', 14.0, 1, 0, 11.2417),
 ('Mrs. Johan (Johanna Persdotter Larsson) Ahlin',
  0,
  3,
  'female',
  40.0,
  1,
  0,
  9.475),
 ('Mrs. William John Robert (Dorothy Ann Wonnacott) Turpin',
  0,
  2,
  'female',
  27.0,
  1,
  0,
  21.0),
 ('Miss. Simonne Marie Anne Andree Laroche',
  1,
  2,
  'female',
  3.0,
  1,
  2,
  41.5792),
 ('Miss. Margaret Delia Devaney', 1, 3, 'female', 19.0, 0, 0, 7.8792),
 ('Mr. William John Rogers', 0, 3, 'male', 30.0, 0, 0, 8.05),
 ('Mr. Denis Lennon', 0, 3, 'male', 20.0, 1, 0, 15.5),
 ("Miss. Bridget O'Driscoll", 1, 3, 'female', 27.0, 0, 0, 7.75),
 ('Mr. Youssef Samaan', 0, 3, 'male', 16.0, 2, 0, 21.6792),
 ('Mrs. Josef (Josefine Franchi) Arnold-Franchi',
  0,
  3,
  'female',
  18.0,
  1,
  0,
  17.8),
 ('Master. Juha Niilo Panula', 0, 3, 'male', 7.0, 4, 1, 39.6875),
 ('Mr. Richard Cater Nosworthy', 0, 3, 'male', 21.0, 0, 0, 7.8),
 ('Mrs. Henry Sleeper (Myna Haxtun) Harper',
  1,
  1,
  'female',
  49.0,
  1,
  0,
  76.7292),
 ('Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunthorpe',
  1,
  2,
  'female',
  29.0,
  1,
  0,
  26.0),
 ('Mr. Engelhart Cornelius Ostby', 0, 1, 'male', 65.0, 0, 1, 61.9792),
 ('Mr. Hugh Woolner', 1, 1, 'male', 46.0, 0, 0, 35.5),
 ('Miss. Emily Rugg', 1, 2, 'female', 21.0, 0, 0, 10.5),
 ('Mr. Mansouer Novel', 0, 3, 'male', 28.5, 0, 0, 7.2292),
 ('Miss. Constance Mirium West', 1, 2, 'female', 5.0, 1, 2, 27.75),
 ('Master. William Frederick Goodwin', 0, 3, 'male', 11.0, 5, 2, 46.9),
 ('Mr. Orsen Sirayanian', 0, 3, 'male', 22.0, 0, 0, 7.2292),
 ('Miss. Amelie Icard', 1, 1, 'female', 38.0, 0, 0, 80.0),
 ('Mr. Henry Birkhardt Harris', 0, 1, 'male', 45.0, 1, 0, 83.475),
 ('Master. Harald Skoog', 0, 3, 'male', 4.0, 3, 2, 27.9),
 ('Mr. Albert A Stewart', 0, 1, 'male', 64.0, 0, 0, 27.7208),
 ('Master. Gerios Moubarek', 1, 3, 'male', 7.0, 1, 1, 15.2458),
 ('Mrs. (Elizabeth Ramell) Nye', 1, 2, 'female', 29.0, 0, 0, 10.5),
 ('Mr. Ernest James Crease', 0, 3, 'male', 19.0, 0, 0, 8.1583),
 ('Miss. Erna Alexandra Andersson', 1, 3, 'female', 17.0, 4, 2, 7.925),
 ('Mr. Vincenz Kink', 0, 3, 'male', 26.0, 2, 0, 8.6625),
 ('Mr. Stephen Curnow Jenkin', 0, 2, 'male', 32.0, 0, 0, 10.5),
 ('Miss. Lillian Amy Goodwin', 0, 3, 'female', 16.0, 5, 2, 46.9),
 ('Mr. Ambrose Jr Hood', 0, 2, 'male', 21.0, 0, 0, 73.5),
 ('Mr. Apostolos Chronopoulos', 0, 3, 'male', 26.0, 1, 0, 14.4542),
 ('Mr. Lee Bing', 1, 3, 'male', 32.0, 0, 0, 56.4958),
 ('Mr. Sigurd Hansen Moen', 0, 3, 'male', 25.0, 0, 0, 7.65),
 ('Mr. Ivan Staneff', 0, 3, 'male', 23.0, 0, 0, 7.8958),
 ('Mr. Rahamin Haim Moutal', 0, 3, 'male', 28.0, 0, 0, 8.05),
 ('Master. Alden Gates Caldwell', 1, 2, 'male', 0.83, 0, 2, 29.0),
 ('Miss. Elizabeth Dowdell', 1, 3, 'female', 30.0, 0, 0, 12.475),
 ('Mr. Achille Waelens', 0, 3, 'male', 22.0, 0, 0, 9.0),
 ('Mr. Jan Baptist Sheerlinck', 1, 3, 'male', 29.0, 0, 0, 9.5),
 ('Miss. Brigdet Delia McDermott', 1, 3, 'female', 31.0, 0, 0, 7.7875),
 ('Mr. Francisco M Carrau', 0, 1, 'male', 28.0, 0, 0, 47.1),
 ('Miss. Bertha Ilett', 1, 2, 'female', 17.0, 0, 0, 10.5),
 ('Mrs. Karl Alfred (Maria Mathilda Gustafsson) Backstrom',
  1,
  3,
  'female',
  33.0,
  3,
  0,
  15.85),
 ('Mr. William Neal Ford', 0, 3, 'male', 16.0, 1, 3, 34.375),
 ('Mr. Selman Francis Slocovski', 0, 3, 'male', 20.0, 0, 0, 8.05),
 ('Miss. Mabel Helen Fortune', 1, 1, 'female', 23.0, 3, 2, 263.0),
 ('Mr. Francesco Celotti', 0, 3, 'male', 24.0, 0, 0, 8.05),
 ('Mr. Emil Christmann', 0, 3, 'male', 29.0, 0, 0, 8.05),
 ('Mr. Paul Edvin Andreasson', 0, 3, 'male', 20.0, 0, 0, 7.8542),
 ('Mr. Herbert Fuller Chaffee', 0, 1, 'male', 46.0, 1, 0, 61.175),
 ('Mr. Bertram Frank Dean', 0, 3, 'male', 26.0, 1, 2, 20.575),
 ('Mr. Daniel Coxon', 0, 3, 'male', 59.0, 0, 0, 7.25),
 ('Mr. Charles Joseph Shorney', 0, 3, 'male', 22.0, 0, 0, 8.05),
 ('Mr. George B Goldschmidt', 0, 1, 'male', 71.0, 0, 0, 34.6542),
 ('Mr. William Bertram Greenfield', 1, 1, 'male', 23.0, 0, 1, 63.3583),
 ('Mrs. John T (Ada Julia Bone) Doling', 1, 2, 'female', 34.0, 0, 1, 23.0),
 ('Mr. Sinai Kantor', 0, 2, 'male', 34.0, 1, 0, 26.0),
 ('Miss. Matilda Petranec', 0, 3, 'female', 28.0, 0, 0, 7.8958),
 ('Mr. Pastcho Petroff', 0, 3, 'male', 29.0, 0, 0, 7.8958),
 ('Mr. Richard Frasar White', 0, 1, 'male', 21.0, 0, 1, 77.2875),
 ('Mr. Gustaf Joel Johansson', 0, 3, 'male', 33.0, 0, 0, 8.6542),
 ('Mr. Anders Vilhelm Gustafsson', 0, 3, 'male', 37.0, 2, 0, 7.925),
 ('Mr. Stoytcho Mionoff', 0, 3, 'male', 28.0, 0, 0, 7.8958),
 ('Miss. Anna Kristine Salkjelsvik', 1, 3, 'female', 21.0, 0, 0, 7.65),
 ('Mr. Albert Johan Moss', 1, 3, 'male', 29.0, 0, 0, 7.775),
 ('Mr. Tido Rekic', 0, 3, 'male', 38.0, 0, 0, 7.8958),
 ('Miss. Bertha Moran', 1, 3, 'female', 28.0, 1, 0, 24.15),
 ('Mr. Walter Chamberlain Porter', 0, 1, 'male', 47.0, 0, 0, 52.0),
 ('Miss. Hileni Zabour', 0, 3, 'female', 14.5, 1, 0, 14.4542),
 ('Mr. David John Barton', 0, 3, 'male', 22.0, 0, 0, 8.05),
 ('Miss. Katriina Jussila', 0, 3, 'female', 20.0, 1, 0, 9.825),
 ('Miss. Malake Attalah', 0, 3, 'female', 17.0, 0, 0, 14.4583),
 ('Mr. Edvard Pekoniemi', 0, 3, 'male', 21.0, 0, 0, 7.925),
 ('Mr. Patrick Connors', 0, 3, 'male', 70.5, 0, 0, 7.75),
 ('Mr. William John Robert Turpin', 0, 2, 'male', 29.0, 1, 0, 21.0),
 ('Mr. Quigg Edmond Baxter', 0, 1, 'male', 24.0, 0, 1, 247.5208),
 ('Miss. Ellis Anna Maria Andersson', 0, 3, 'female', 2.0, 4, 2, 31.275),
 ('Mr. Stanley George Hickman', 0, 2, 'male', 21.0, 2, 0, 73.5),
 ('Mr. Leonard Charles Moore', 0, 3, 'male', 19.0, 0, 0, 8.05),
 ('Mr. Nicholas Nasser', 0, 2, 'male', 32.5, 1, 0, 30.0708),
 ('Miss. Susan Webber', 1, 2, 'female', 32.5, 0, 0, 13.0),
 ('Mr. Percival Wayland White', 0, 1, 'male', 54.0, 0, 1, 77.2875),
 ('Master. Elias Nicola-Yarred', 1, 3, 'male', 12.0, 1, 0, 11.2417),
 ('Mr. Martin McMahon', 0, 3, 'male', 19.0, 0, 0, 7.75),
 ('Mr. Fridtjof Arne Madsen', 1, 3, 'male', 24.0, 0, 0, 7.1417),
 ('Miss. Anna Peter', 1, 3, 'female', 2.0, 1, 1, 22.3583),
 ('Mr. Johan Ekstrom', 0, 3, 'male', 45.0, 0, 0, 6.975),
 ('Mr. Jozef Drazenoic', 0, 3, 'male', 33.0, 0, 0, 7.8958),
 ('Mr. Domingos Fernandeo Coelho', 0, 3, 'male', 20.0, 0, 0, 7.05),
 ('Mrs. Alexander A (Grace Charity Laury) Robins',
  0,
  3,
  'female',
  47.0,
  1,
  0,
  14.5),
 ('Mrs. Leopold (Mathilde Francoise Pede) Weisz',
  1,
  2,
  'female',
  29.0,
  1,
  0,
  26.0),
 ('Mr. Samuel James Hayden Sobey', 0, 2, 'male', 25.0, 0, 0, 13.0),
 ('Mr. Emile Richard', 0, 2, 'male', 23.0, 0, 0, 15.0458),
 ('Miss. Helen Monypeny Newsom', 1, 1, 'female', 19.0, 0, 2, 26.2833),
 ('Mr. Jacques Heath Futrelle', 0, 1, 'male', 37.0, 1, 0, 53.1),
 ('Mr. Olaf Elon Osen', 0, 3, 'male', 16.0, 0, 0, 9.2167),
 ('Mr. Victor Giglio', 0, 1, 'male', 24.0, 0, 0, 79.2),
 ('Mrs. Joseph (Sultana) Boulos', 0, 3, 'female', 40.0, 0, 2, 15.2458),
 ('Miss. Anna Sofia Nysten', 1, 3, 'female', 22.0, 0, 0, 7.75),
 ('Mrs. Pekka Pietari (Elin Matilda Dolck) Hakkarainen',
  1,
  3,
  'female',
  24.0,
  1,
  0,
  15.85),
 ('Mr. Jeremiah Burke', 0, 3, 'male', 19.0, 0, 0, 6.75),
 ('Mr. Edgardo Samuel Andrew', 0, 2, 'male', 18.0, 0, 0, 11.5),
 ('Mr. Joseph Charles Nicholls', 0, 2, 'male', 19.0, 1, 1, 36.75),
 ('Mr. August Edvard Andersson', 1, 3, 'male', 27.0, 0, 0, 7.7958),
 ('Miss. Robina Maggie Ford', 0, 3, 'female', 9.0, 2, 2, 34.375),
 ('Mr. Michel Navratil', 0, 2, 'male', 36.5, 0, 2, 26.0),
 ('Rev. Thomas Roussel Davids Byles', 0, 2, 'male', 42.0, 0, 0, 13.0),
 ('Rev. Robert James Bateman', 0, 2, 'male', 51.0, 0, 0, 12.525),
 ('Mrs. Thomas (Edith Wearne) Pears', 1, 1, 'female', 22.0, 1, 0, 66.6),
 ('Mr. Alfonzo Meo', 0, 3, 'male', 55.5, 0, 0, 8.05),
 ('Mr. Austin Blyler van Billiard', 0, 3, 'male', 40.5, 0, 2, 14.5),
 ('Mr. Ole Martin Olsen', 0, 3, 'male', 27.0, 0, 0, 7.3125),
 ('Mr. Charles Duane Williams', 0, 1, 'male', 51.0, 0, 1, 61.3792),
 ('Miss. Katherine Gilnagh', 1, 3, 'female', 16.0, 0, 0, 7.7333),
 ('Mr. Harry Corn', 0, 3, 'male', 30.0, 0, 0, 8.05),
 ('Mr. Mile Smiljanic', 0, 3, 'male', 37.0, 0, 0, 8.6625),
 ('Master. Thomas Henry Sage', 0, 3, 'male', 5.0, 8, 2, 69.55),
 ('Mr. John Hatfield Cribb', 0, 3, 'male', 44.0, 0, 1, 16.1),
 ('Mrs. James (Elizabeth Inglis Milne) Watt',
  1,
  2,
  'female',
  40.0,
  0,
  0,
  15.75),
 ('Mr. John Viktor Bengtsson', 0, 3, 'male', 26.0, 0, 0, 7.775),
 ('Mr. Jovo Calic', 0, 3, 'male', 17.0, 0, 0, 8.6625),
 ('Master. Eino Viljami Panula', 0, 3, 'male', 1.0, 4, 1, 39.6875),
 ('Master. Frank John William Goldsmith', 1, 3, 'male', 9.0, 0, 2, 20.525),
 ('Mrs. (Edith Martha Bowerman) Chibnall', 1, 1, 'female', 48.0, 0, 1, 55.0),
 ('Mrs. William (Anna Bernhardina Karlsson) Skoog',
  0,
  3,
  'female',
  45.0,
  1,
  4,
  27.9),
 ('Mr. John D Baumann', 0, 1, 'male', 60.0, 0, 0, 25.925),
 ('Mr. Lee Ling', 0, 3, 'male', 28.0, 0, 0, 56.4958),
 ('Mr. Wyckoff Van der hoef', 0, 1, 'male', 61.0, 0, 0, 33.5),
 ('Master. Arthur Rice', 0, 3, 'male', 4.0, 4, 1, 29.125),
 ('Miss. Eleanor Ileen Johnson', 1, 3, 'female', 1.0, 1, 1, 11.1333),
 ('Mr. Antti Wilhelm Sivola', 0, 3, 'male', 21.0, 0, 0, 7.925),
 ('Mr. James Clinch Smith', 0, 1, 'male', 56.0, 0, 0, 30.6958),
 ('Mr. Klas Albin Klasen', 0, 3, 'male', 18.0, 1, 1, 7.8542),
 ('Master. Henry Forbes Lefebre', 0, 3, 'male', 5.0, 3, 1, 25.4667),
 ('Miss. Ann Elizabeth Isham', 0, 1, 'female', 50.0, 0, 0, 28.7125),
 ('Mr. Reginald Hale', 0, 2, 'male', 30.0, 0, 0, 13.0),
 ('Mr. Lionel Leonard', 0, 3, 'male', 36.0, 0, 0, 0.0),
 ('Miss. Constance Gladys Sage', 0, 3, 'female', 8.0, 8, 2, 69.55),
 ('Mr. Rene Pernot', 0, 2, 'male', 39.0, 0, 0, 15.05),
 ('Master. Clarence Gustaf Hugo Asplund', 0, 3, 'male', 9.0, 4, 2, 31.3875),
 ('Master. Richard F Becker', 1, 2, 'male', 1.0, 2, 1, 39.0),
 ('Miss. Luise Gretchen Kink-Heilmann', 1, 3, 'female', 4.0, 0, 2, 22.025),
 ('Mr. Hugh Roscoe Rood', 0, 1, 'male', 39.0, 0, 0, 50.0),
 ("Mrs. Thomas (Johanna Godfrey) O'Brien", 1, 3, 'female', 26.0, 1, 0, 15.5),
 ('Mr. Charles Hallace Romaine', 1, 1, 'male', 45.0, 0, 0, 26.55),
 ('Mr. John Bourke', 0, 3, 'male', 40.0, 1, 1, 15.5),
 ('Mr. Stjepan Turcin', 0, 3, 'male', 36.0, 0, 0, 7.8958),
 ('Mrs. (Rosa) Pinsky', 1, 2, 'female', 32.0, 0, 0, 13.0),
 ('Mr. William Carbines', 0, 2, 'male', 19.0, 0, 0, 13.0),
 ('Miss. Carla Christine Nielsine Andersen-Jensen',
  1,
  3,
  'female',
  19.0,
  1,
  0,
  7.8542),
 ('Master. Michel M Navratil', 1, 2, 'male', 3.0, 1, 1, 26.0),
 ('Mrs. James Joseph (Margaret Tobin) Brown',
  1,
  1,
  'female',
  44.0,
  0,
  0,
  27.7208),
 ('Miss. Elise Lurette', 1, 1, 'female', 58.0, 0, 0, 146.5208),
 ('Mr. Robert Mernagh', 0, 3, 'male', 28.0, 0, 0, 7.75),
 ('Mr. Karl Siegwart Andreas Olsen', 0, 3, 'male', 42.0, 0, 1, 8.4042),
 ('Miss. Margaret Madigan', 1, 3, 'female', 21.0, 0, 0, 7.75),
 ('Miss. Henriette Yrois', 0, 2, 'female', 24.0, 0, 0, 13.0),
 ('Mr. Nestor Cyriel Vande Walle', 0, 3, 'male', 28.0, 0, 0, 9.5),
 ('Mr. Frederick Sage', 0, 3, 'male', 17.0, 8, 2, 69.55),
 ('Mr. Jakob Alfred Johanson', 0, 3, 'male', 34.0, 0, 0, 6.4958),
 ('Mr. Gerious Youseff', 0, 3, 'male', 45.5, 0, 0, 7.225),
 ('Mr. Gurshon Cohen', 1, 3, 'male', 18.0, 0, 0, 8.05),
 ('Miss. Telma Matilda Strom', 0, 3, 'female', 2.0, 0, 1, 10.4625),
 ('Mr. Karl Alfred Backstrom', 0, 3, 'male', 32.0, 1, 0, 15.85),
 ('Mr. Nassef Cassem Albimona', 1, 3, 'male', 26.0, 0, 0, 18.7875),
 ('Miss. Helen Carr', 1, 3, 'female', 16.0, 0, 0, 7.75),
 ('Mr. Henry Blank', 1, 1, 'male', 40.0, 0, 0, 31.0),
 ('Mr. Ahmed Ali', 0, 3, 'male', 24.0, 0, 0, 7.05),
 ('Miss. Clear Annie Cameron', 1, 2, 'female', 35.0, 0, 0, 21.0),
 ('Mr. John Henry Perkin', 0, 3, 'male', 22.0, 0, 0, 7.25),
 ('Mr. Hans Kristensen Givard', 0, 2, 'male', 30.0, 0, 0, 13.0),
 ('Mr. Philip Kiernan', 0, 3, 'male', 22.0, 1, 0, 7.75),
 ('Miss. Madeleine Newell', 1, 1, 'female', 31.0, 1, 0, 113.275),
 ('Miss. Eliina Honkanen', 1, 3, 'female', 27.0, 0, 0, 7.925),
 ('Mr. Sidney Samuel Jacobsohn', 0, 2, 'male', 42.0, 1, 0, 27.0),
 ('Miss. Albina Bazzani', 1, 1, 'female', 32.0, 0, 0, 76.2917),
 ('Mr. Walter Harris', 0, 2, 'male', 30.0, 0, 0, 10.5),
 ('Mr. Victor Francis Sunderland', 1, 3, 'male', 16.0, 0, 0, 8.05),
 ('Mr. James H Bracken', 0, 2, 'male', 27.0, 0, 0, 13.0),
 ('Mr. George Henry Green', 0, 3, 'male', 51.0, 0, 0, 8.05),
 ('Mr. Christo Nenkoff', 0, 3, 'male', 22.0, 0, 0, 7.8958),
 ('Mr. Frederick Maxfield Hoyt', 1, 1, 'male', 38.0, 1, 0, 90.0),
 ('Mr. Karl Ivar Sven Berglund', 0, 3, 'male', 22.0, 0, 0, 9.35),
 ('Mr. William John Mellors', 1, 2, 'male', 19.0, 0, 0, 10.5),
 ('Mr. John Hall Lovell', 0, 3, 'male', 20.5, 0, 0, 7.25),
 ('Mr. Arne Jonas Fahlstrom', 0, 2, 'male', 18.0, 0, 0, 13.0),
 ('Miss. Mathilde Lefebre', 0, 3, 'female', 12.0, 3, 1, 25.4667),
 ('Mrs. Henry Birkhardt (Irene Wallach) Harris',
  1,
  1,
  'female',
  35.0,
  1,
  0,
  83.475),
 ('Mr. Bengt Edvin Larsson', 0, 3, 'male', 29.0, 0, 0, 7.775),
 ('Mr. Ernst Adolf Sjostedt', 0, 2, 'male', 59.0, 0, 0, 13.5),
 ('Miss. Lillian Gertrud Asplund', 1, 3, 'female', 5.0, 4, 2, 31.3875),
 ('Mr. Robert William Norman Leyson', 0, 2, 'male', 24.0, 0, 0, 10.5),
 ('Miss. Alice Phoebe Harknett', 0, 3, 'female', 21.0, 0, 0, 7.55),
 ('Mr. Stephen Hold', 0, 2, 'male', 44.0, 1, 0, 26.0),
 ('Miss. Marjorie Collyer', 1, 2, 'female', 8.0, 0, 2, 26.25),
 ('Mr. Frederick William Pengelly', 0, 2, 'male', 19.0, 0, 0, 10.5),
 ('Mr. George Henry Hunt', 0, 2, 'male', 33.0, 0, 0, 12.275),
 ('Miss. Thamine Zabour', 0, 3, 'female', 19.0, 1, 0, 14.4542),
 ('Miss. Katherine Murphy', 1, 3, 'female', 18.0, 1, 0, 15.5),
 ('Mr. Reginald Charles Coleridge', 0, 2, 'male', 29.0, 0, 0, 10.5),
 ('Mr. Matti Alexanteri Maenpaa', 0, 3, 'male', 22.0, 0, 0, 7.125),
 ('Mr. Sleiman Attalah', 0, 3, 'male', 30.0, 0, 0, 7.225),
 ('Dr. William Edward Minahan', 0, 1, 'male', 44.0, 2, 0, 90.0),
 ('Miss. Agda Thorilda Viktoria Lindahl', 0, 3, 'female', 25.0, 0, 0, 7.775),
 ('Mrs. William (Anna) Hamalainen', 1, 2, 'female', 24.0, 0, 2, 14.5),
 ('Mr. Richard Leonard Beckwith', 1, 1, 'male', 37.0, 1, 1, 52.5542),
 ('Rev. Ernest Courtenay Carter', 0, 2, 'male', 54.0, 1, 0, 26.0),
 ('Mr. James George Reed', 0, 3, 'male', 18.0, 0, 0, 7.25),
 ('Mrs. Wilhelm (Elna Matilda Persson) Strom',
  0,
  3,
  'female',
  29.0,
  1,
  1,
  10.4625),
 ('Mr. William Thomas Stead', 0, 1, 'male', 62.0, 0, 0, 26.55),
 ('Mr. William Arthur Lobb', 0, 3, 'male', 30.0, 1, 0, 16.1),
 ('Mrs. Viktor (Helena Wilhelmina) Rosblom',
  0,
  3,
  'female',
  41.0,
  0,
  2,
  20.2125),
 ('Mrs. Darwis (Hanne Youssef Razi) Touma',
  1,
  3,
  'female',
  29.0,
  0,
  2,
  15.2458),
 ('Mrs. Gertrude Maybelle Thorne', 1, 1, 'female', 38.0, 0, 0, 79.2),
 ('Miss. Gladys Cherry', 1, 1, 'female', 30.0, 0, 0, 86.5),
 ('Miss. Anna Ward', 1, 1, 'female', 35.0, 0, 0, 512.3292),
 ('Mrs. (Lutie Davis) Parrish', 1, 2, 'female', 50.0, 0, 1, 26.0),
 ('Master. Edvin Rojj Felix Asplund', 1, 3, 'male', 3.0, 4, 2, 31.3875),
 ('Mr. Emil Taussig', 0, 1, 'male', 52.0, 1, 1, 79.65),
 ('Mr. William Harrison', 0, 1, 'male', 40.0, 0, 0, 0.0),
 ('Miss. Delia Henry', 0, 3, 'female', 21.0, 0, 0, 7.75),
 ('Mr. David Reeves', 0, 2, 'male', 36.0, 0, 0, 10.5),
 ('Mr. Ernesti Arvid Panula', 0, 3, 'male', 16.0, 4, 1, 39.6875),
 ('Mr. Ernst Ulrik Persson', 1, 3, 'male', 25.0, 1, 0, 7.775),
 ('Mrs. William Thompson (Edith Junkins) Graham',
  1,
  1,
  'female',
  58.0,
  0,
  1,
  153.4625),
 ('Miss. Amelia Bissette', 1, 1, 'female', 35.0, 0, 0, 135.6333),
 ('Mr. Alexander Cairns', 0, 1, 'male', 28.0, 0, 0, 31.0),
 ('Mr. William Henry Tornquist', 1, 3, 'male', 25.0, 0, 0, 0.0),
 ('Mrs. (Elizabeth Anne Maidment) Mellinger',
  1,
  2,
  'female',
  41.0,
  0,
  1,
  19.5),
 ('Mr. Charles H Natsch', 0, 1, 'male', 37.0, 0, 1, 29.7),
 ('Miss. Hanora Healy', 1, 3, 'female', 33.0, 0, 0, 7.75),
 ('Miss. Kornelia Theodosia Andrews', 1, 1, 'female', 63.0, 1, 0, 77.9583),
 ('Miss. Augusta Charlotta Lindblom', 0, 3, 'female', 45.0, 0, 0, 7.75),
 ('Mr. Francis Parkes', 0, 2, 'male', 21.0, 0, 0, 0.0),
 ('Master. Eric Rice', 0, 3, 'male', 7.0, 4, 1, 29.125),
 ('Mrs. Stanton (Rosa Hunt) Abbott', 1, 3, 'female', 35.0, 1, 1, 20.25),
 ('Mr. Frank Duane', 0, 3, 'male', 65.0, 0, 0, 7.75),
 ('Mr. Nils Johan Goransson Olsson', 0, 3, 'male', 28.0, 0, 0, 7.8542),
 ('Mr. Alfons de Pelsmaeker', 0, 3, 'male', 16.0, 0, 0, 9.5),
 ('Mr. Edward Arthur Dorking', 1, 3, 'male', 19.0, 0, 0, 8.05),
 ('Mr. Richard William Smith', 0, 1, 'male', 57.0, 0, 0, 26.0),
 ('Mr. Ivan Stankovic', 0, 3, 'male', 33.0, 0, 0, 8.6625),
 ('Mr. Theodore de Mulder', 1, 3, 'male', 30.0, 0, 0, 9.5),
 ('Mr. Penko Naidenoff', 0, 3, 'male', 22.0, 0, 0, 7.8958),
 ('Mr. Masabumi Hosono', 1, 2, 'male', 42.0, 0, 0, 13.0),
 ('Miss. Kate Connolly', 1, 3, 'female', 22.0, 0, 0, 7.75),
 ('Miss. Ellen Barber', 1, 1, 'female', 26.0, 0, 0, 78.85),
 ('Mrs. Dickinson H (Helen Walton) Bishop',
  1,
  1,
  'female',
  19.0,
  1,
  0,
  91.0792),
 ('Mr. Rene Jacques Levy', 0, 2, 'male', 36.0, 0, 0, 12.875),
 ('Miss. Aloisia Haas', 0, 3, 'female', 24.0, 0, 0, 8.85),
 ('Mr. Ivan Mineff', 0, 3, 'male', 24.0, 0, 0, 7.8958),
 ('Mr. Ervin G Lewy', 0, 1, 'male', 30.0, 0, 0, 27.7208),
 ('Mr. Mansour Hanna', 0, 3, 'male', 23.5, 0, 0, 7.2292),
 ('Miss. Helen Loraine Allison', 0, 1, 'female', 2.0, 1, 2, 151.55),
 ('Mr. Adolphe Saalfeld', 1, 1, 'male', 47.0, 0, 0, 30.5),
 ('Mrs. James (Helene DeLaudeniere Chaput) Baxter',
  1,
  1,
  'female',
  50.0,

In [12]:
pg_cur.execute('Select * FROM "public"."Titanic" LIMIT 0')
colnames = [desc[0] for desc in pg_cur.description]
colnames

['Name',
 'Survived',
 'Pclass',
 'Sex',
 'Age',
 'Siblings/Spouses Aboard',
 'Parents/Children Aboard',
 'Fare']

In [21]:
# - How many passengers survived, and how many died?
query = """
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Survived" = 1
"""
pg_cur.execute(query)
len(pg_cur.fetchall())

342

In [22]:
query = """
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Survived" = 0
"""
pg_cur.execute(query)
len(pg_cur.fetchall())

545

In [23]:
# - How many passengers were in each class?
query = """
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 1
"""
pg_cur.execute(query)
print("First Class", len(pg_cur.fetchall()))

query = """
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 2
"""
pg_cur.execute(query)
print("Second Class", len(pg_cur.fetchall()))

query = """
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 3
"""
pg_cur.execute(query)
print("Third Class", len(pg_cur.fetchall()))

First Class 216
Second Class 184
Third Class 487

In [31]:
# - How many passengers survived/died within each class?
query = """
SELECT * FROM (
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 1
) AS c WHERE c."Survived" = 1;
"""
pg_cur.execute(query)
print("First class survivors: ", len(pg_cur.fetchall()))

query = """
SELECT * FROM (
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 1
) AS c WHERE c."Survived" = 0;
"""
pg_cur.execute(query)
print("First class deaths: ", len(pg_cur.fetchall()))


query = """
SELECT * FROM (
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 2
) AS c WHERE c."Survived" = 1;
"""
pg_cur.execute(query)
print("Second class survivors: ", len(pg_cur.fetchall()))

query = """
SELECT * FROM (
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 2
) AS c WHERE c."Survived" = 0;
"""
pg_cur.execute(query)
print("Second class deaths: ", len(pg_cur.fetchall()))


query = """
SELECT * FROM (
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 3
) AS c WHERE c."Survived" = 1;
"""
pg_cur.execute(query)
print("Third class survivors: ", len(pg_cur.fetchall()))

query = """
SELECT * FROM (
SELECT * FROM "public"."Titanic" WHERE "Titanic"."Pclass" = 3
) AS c WHERE c."Survived" = 0;
"""
pg_cur.execute(query)
print("Third class deaths: ", len(pg_cur.fetchall()))

First class survivors:  136
First class deaths:  80
Second class survivors:  87
Second class deaths:  97
Third class survivors:  119
Third class deaths:  368

In [40]:
# - What was the average age of survivors vs nonsurvivors?
query = """
SELECT AVG("Titanic"."Age") FROM "public"."Titanic"
WHERE "Titanic"."Survived" = 0
"""
pg_cur.execute(query)
print("Average age of non-survivors: ", pg_cur.fetchone()[0])

query = """
SELECT AVG("Titanic"."Age") FROM "public"."Titanic"
WHERE "Titanic"."Survived" = 1
"""
pg_cur.execute(query)
print("Average age of survivors: ", pg_cur.fetchone()[0])

Average age of non-survivors:  30.1385321100917
Average age of survivors:  28.4083918128655

In [44]:
# - What was the average age of each passenger class?
for i in [1, 2, 3]:
    query = f"""
    SELECT AVG("Titanic"."Age") FROM "public"."Titanic"
    WHERE "Titanic"."Pclass" = {i}
    """
    pg_cur.execute(query)
    print(f"Average age of class {i} passengers: {pg_cur.fetchone()[0]}")

Average age of class 1 passengers: 38.7889814814815
Average age of class 2 passengers: 29.8686413043478
Average age of class 3 passengers: 25.1887474332649

In [46]:
# - What was the average fare by passenger class? By survival?
for i in [1, 2, 3]:
    query = f"""
    SELECT AVG("Titanic"."Fare") FROM "public"."Titanic"
    WHERE "Titanic"."Pclass" = {i}
    """
    pg_cur.execute(query)
    print(f"Average fare of class {i} passengers: {pg_cur.fetchone()[0]}")
    
for i in [0, 1]:
    query = f"""
    SELECT AVG("Titanic"."Fare") FROM "public"."Titanic"
    WHERE "Titanic"."Survived" = {i}
    """
    pg_cur.execute(query)
    print(f"Average fare of {'non-' if i-1 else ''}survivor: {pg_cur.fetchone()[0]}")

Average fare of class 1 passengers: 84.1546874999999
Average fare of class 2 passengers: 20.6621831521739
Average fare of class 3 passengers: 13.7077073921971
Average fare of non-survivor: 22.2085840366972
Average fare of survivor: 48.3954076023392

In [47]:
# - How many siblings/spouses aboard on average, by passenger class? By survival?
for i in [1, 2, 3]:
    query = f"""
    SELECT AVG("Titanic"."Siblings/Spouses Aboard") FROM "public"."Titanic"
    WHERE "Titanic"."Pclass" = {i}
    """
    pg_cur.execute(query)
    print(f"Average Siblings/Spouses Aboard of class {i} passengers: {pg_cur.fetchone()[0]}")
    
for i in [0, 1]:
    query = f"""
    SELECT AVG("Titanic"."Siblings/Spouses Aboard") FROM "public"."Titanic"
    WHERE "Titanic"."Survived" = {i}
    """
    pg_cur.execute(query)
    print(f"Average Siblings/Spouses Aboard of {'non-' if i-1 else ''}survivor: {pg_cur.fetchone()[0]}")

Average Siblings/Spouses Aboard of class 1 passengers: 0.41666666666666666667
Average Siblings/Spouses Aboard of class 2 passengers: 0.40217391304347826087
Average Siblings/Spouses Aboard of class 3 passengers: 0.62012320328542094456
Average Siblings/Spouses Aboard of non-survivor: 0.55779816513761467890
Average Siblings/Spouses Aboard of survivor: 0.47368421052631578947

In [48]:
# - How many parents/children aboard on average, by passenger class? By survival?
for i in [1, 2, 3]:
    query = f"""
    SELECT AVG("Titanic"."Parents/Children Aboard") FROM "public"."Titanic"
    WHERE "Titanic"."Pclass" = {i}
    """
    pg_cur.execute(query)
    print(f"Average Parents/Children Aboard of class {i} passengers: {pg_cur.fetchone()[0]}")
    
for i in [0, 1]:
    query = f"""
    SELECT AVG("Titanic"."Parents/Children Aboard") FROM "public"."Titanic"
    WHERE "Titanic"."Survived" = {i}
    """
    pg_cur.execute(query)
    print(f"Average Parents/Children Aboard of {'non-' if i-1 else ''}survivor: {pg_cur.fetchone()[0]}")

Average Parents/Children Aboard of class 1 passengers: 0.35648148148148148148
Average Parents/Children Aboard of class 2 passengers: 0.38043478260869565217
Average Parents/Children Aboard of class 3 passengers: 0.39630390143737166324
Average Parents/Children Aboard of non-survivor: 0.33211009174311926606
Average Parents/Children Aboard of survivor: 0.46491228070175438596

In [59]:
# - Do any passengers have the same name?
query = """
SELECT COUNT("Titanic"."Name") AS c
FROM "public"."Titanic"
GROUP BY "Titanic"."Name"
ORDER BY c DESC
"""
pg_cur.execute(query)
pg_cur.fetchone() != (1,)

False

In [66]:
# - (Bonus! Hard, may require pulling and processing with Python) How many married
#   couples were aboard the Titanic? Assume that two people (one `Mr.` and one
#   `Mrs.`) with the same last name and with at least 1 sibling/spouse aboard are
#   a married couple.
query = """
SELECT "Titanic"."Name" as n
FROM "public"."Titanic"
WHERE "Titanic"."Siblings/Spouses Aboard" > 0
"""
pg_cur.execute(query)
names = pg_cur.fetchall()
names

[('Mr. Owen Harris Braund',),
 ('Mrs. John Bradley (Florence Briggs Thayer) Cumings',),
 ('Mrs. Jacques Heath (Lily May Peel) Futrelle',),
 ('Master. Gosta Leonard Palsson',),
 ('Mrs. Nicholas (Adele Achem) Nasser',),
 ('Miss. Marguerite Rut Sandstrom',),
 ('Mr. Anders Johan Andersson',),
 ('Master. Eugene Rice',),
 ('Mrs. Julius (Emelia Maria Vandemoortele) Vander Planke',),
 ('Miss. Torborg Danira Palsson',),
 ('Mrs. Carl Oscar (Selma Augusta Emilia Johansson) Asplund',),
 ('Mr. Charles Alexander Fortune',),
 ('Mrs. William Augustus (Marie Eugenie) Spencer',),
 ('Mr. Edgar Joseph Meyer',),
 ('Mr. Alexander Oskar Holverson',),
 ('Miss. Augusta Maria Vander Planke',),
 ('Miss. Jamila Nicola-Yarred',),
 ('Mrs. Johan (Johanna Persdotter Larsson) Ahlin',),
 ('Mrs. William John Robert (Dorothy Ann Wonnacott) Turpin',),
 ('Miss. Simonne Marie Anne Andree Laroche',),
 ('Mr. Denis Lennon',),
 ('Mr. Youssef Samaan',),
 ('Mrs. Josef (Josefine Franchi) Arnold-Franchi',),
 ('Master. Juha Niilo Panula',),
 ('Mrs. Henry Sleeper (Myna Haxtun) Harper',),
 ('Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunthorpe',),
 ('Miss. Constance Mirium West',),
 ('Master. William Frederick Goodwin',),
 ('Mr. Henry Birkhardt Harris',),
 ('Master. Harald Skoog',),
 ('Master. Gerios Moubarek',),
 ('Miss. Erna Alexandra Andersson',),
 ('Mr. Vincenz Kink',),
 ('Miss. Lillian Amy Goodwin',),
 ('Mr. Apostolos Chronopoulos',),
 ('Mrs. Karl Alfred (Maria Mathilda Gustafsson) Backstrom',),
 ('Mr. William Neal Ford',),
 ('Miss. Mabel Helen Fortune',),
 ('Mr. Herbert Fuller Chaffee',),
 ('Mr. Bertram Frank Dean',),
 ('Mr. Sinai Kantor',),
 ('Mr. Anders Vilhelm Gustafsson',),
 ('Miss. Bertha Moran',),
 ('Miss. Hileni Zabour',),
 ('Miss. Katriina Jussila',),
 ('Mr. William John Robert Turpin',),
 ('Miss. Ellis Anna Maria Andersson',),
 ('Mr. Stanley George Hickman',),
 ('Mr. Nicholas Nasser',),
 ('Master. Elias Nicola-Yarred',),
 ('Miss. Anna Peter',),
 ('Mrs. Alexander A (Grace Charity Laury) Robins',),
 ('Mrs. Leopold (Mathilde Francoise Pede) Weisz',),
 ('Mr. Jacques Heath Futrelle',),
 ('Mrs. Pekka Pietari (Elin Matilda Dolck) Hakkarainen',),
 ('Mr. Joseph Charles Nicholls',),
 ('Miss. Robina Maggie Ford',),
 ('Mrs. Thomas (Edith Wearne) Pears',),
 ('Master. Thomas Henry Sage',),
 ('Master. Eino Viljami Panula',),
 ('Mrs. William (Anna Bernhardina Karlsson) Skoog',),
 ('Master. Arthur Rice',),
 ('Miss. Eleanor Ileen Johnson',),
 ('Mr. Klas Albin Klasen',),
 ('Master. Henry Forbes Lefebre',),
 ('Miss. Constance Gladys Sage',),
 ('Master. Clarence Gustaf Hugo Asplund',),
 ('Master. Richard F Becker',),
 ("Mrs. Thomas (Johanna Godfrey) O'Brien",),
 ('Mr. John Bourke',),
 ('Miss. Carla Christine Nielsine Andersen-Jensen',),
 ('Master. Michel M Navratil',),
 ('Mr. Frederick Sage',),
 ('Mr. Karl Alfred Backstrom',),
 ('Mr. Philip Kiernan',),
 ('Miss. Madeleine Newell',),
 ('Mr. Sidney Samuel Jacobsohn',),
 ('Mr. Frederick Maxfield Hoyt',),
 ('Miss. Mathilde Lefebre',),
 ('Mrs. Henry Birkhardt (Irene Wallach) Harris',),
 ('Miss. Lillian Gertrud Asplund',),
 ('Mr. Stephen Hold',),
 ('Miss. Thamine Zabour',),
 ('Miss. Katherine Murphy',),
 ('Dr. William Edward Minahan',),
 ('Mr. Richard Leonard Beckwith',),
 ('Rev. Ernest Courtenay Carter',),
 ('Mrs. Wilhelm (Elna Matilda Persson) Strom',),
 ('Mr. William Arthur Lobb',),
 ('Master. Edvin Rojj Felix Asplund',),
 ('Mr. Emil Taussig',),
 ('Mr. Ernesti Arvid Panula',),
 ('Mr. Ernst Ulrik Persson',),
 ('Miss. Kornelia Theodosia Andrews',),
 ('Master. Eric Rice',),
 ('Mrs. Stanton (Rosa Hunt) Abbott',),
 ('Mrs. Dickinson H (Helen Walton) Bishop',),
 ('Miss. Helen Loraine Allison',),
 ('Mr. Bernard McCoy',),
 ('Master. Hudson Trevor Allison',),
 ('Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo) Penasco y Castellana',),
 ('Mr. Samuel Abelson',),
 ('Miss. Emily Borie Ryerson',),
 ('Mrs. William (Anna Sylfven) Lahtinen',),
 ('Mr. Benjamin Hart',),
 ('Mrs. Sinai (Miriam Sternin) Kantor',),
 ('Mrs. Frederic Oakley (Margaretta Corning Stone) Spedden',),
 ('Mrs. Albert Francis (Sylvia Mae Harbaugh) Caldwell',),
 ('Mr. George John Jr Sage',),
 ('Mrs. Frank John (Emily Alice Brown) Goldsmith',),
 ('Miss. Agnes McCoy',),
 ('Mr. Leo Edmondus Vander Planke',),
 ('Mrs. Henry William (Clara Heinsheimer) Frauenthal',),
 ('Mr. Thomas Clinton Pears',),
 ('Master. Edmond Roger Navratil',),
 ('Miss. Alice Elizabeth Fortune',),
 ('Mrs. Thomas Henry (Mary E Finck) Davison',),
 ('Master. William Loch Coutts',),
 ('Mr. Tannous Elias',),
 ('Mr. Josef Arnold-Franchi',),
 ('Mr. Wilhelm Skoog',),
 ('Mr. Sebastiano del Carlo',),
 ("Mr. Thomas O'Brien",),
 ('Mrs. Frank Manley (Anna Sophia Atkinson) Warren',),
 ('Mr. George Achilles Harder',),
 ('Mr. Jakob Alfred Wiklund',),
 ('Miss. Stina Viola Palsson',),
 ('Mrs. Edgar Joseph (Leila Saks) Meyer',),
 ('Mrs. Alexander Oskar (Mary Aline Towner) Holverson',),
 ('Master. Sidney Leonard Goodwin',),
 ('Mr. William Ernest Carter',),
 ('Mr. Johan Birger Gustafsson',),
 ('Miss. Marjorie Newell',),
 ('Miss. Mari Aina Jussila',),
 ('Mr. Pekka Pietari Hakkarainen',),
 ('Mr. Shadrach Gale',),
 ('Master. William Rowe Richards',),
 ('Miss. Ida Lefebre',),
 ('Miss. Daisy E Minahan',),
 ('Mrs. James Vivian (Lulu Thorne Christian) Drew',),
 ('Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren) Danbom',),
 ('Mr. Viktor Richard Rosblom',),
 ('Mrs. Charles V (Ada Maria Winfield) Clarke',),
 ('Mrs. Percival (Florence Kate White) Thorneycroft',),
 ('Mrs. Charles Alexander (Alice Adelaide Slow) Louch',),
 ('Mr. William Baird Silvey',),
 ('Miss. Lucile Polk Carter',),
 ('Miss. Doolina Margaret Ford',),
 ('Mrs. Sidney (Emily Hocking) Richards',),
 ('Mr. Mark Fortune',),
 ('Mrs. Benjamin (Esther Ada Bloomfield) Hart',),
 ('Mr. Johan Emil Petterson',),
 ('Miss. Marie Catherine Baclini',),
 ('Mr. Edwy Arthur West',),
 ('Mr. Ingvald Olai Olsen Hagland',),
 ('Mr. Samuel L Goldenberg',),
 ('Mrs. Frederick R (Marion) Kenyon',),
 ('Miss. Helene Barbara Baclini',),
 ('Mrs. Edwy Arthur (Ada Mary Worth) West',),
 ('Mr. Peter Henry Renouf',),
 ('Mr. Lewis Richard Braund',),
 ('Master. Harold Victor Goodwin',),
 ('Mr. Dickinson H Bishop',),
 ('Miss. Jeannie Lefebre',),
 ('Mrs. Frederick Maxfield (Jane Anne Forby) Hoyt',),
 ('Master. Eden Leslie Coutts',),
 ('Mr. Konrad Mathias Reiersen Hagland',),
 ('Miss. Elizabeth Mussey Eustis',),
 ('Mrs. Hudson J C (Bessie Waldo Daniels) Allison',),
 ('Mr. Victor de Satode Penasco y Castellana',),
 ('Mrs. Martin (Elizabeth L. Barrett) Rothschild',),
 ('Mrs. William A (Florence Agnes Hughes) Angle',),
 ('Mr. Richard George Hocking',),
 ('Miss. Phyllis May Quick',),
 ('Mr. Joseph Jr Elias',),
 ('Miss. Ingeborg Constanzia Andersson',),
 ('Miss. Sigrid Elisabeth Andersson',),
 ('Mr. Edward Beane',),
 ('Mr. Walter Donald Douglas',),
 ('Mrs. Edward (Ethel Clarke) Beane',),
 ('Mr. Frank John Goldsmith',),
 ('Master. John Morgan Jr Davies',),
 ('Lady. (Lucille Christiana Sutherland)Duff Gordon',),
 ('Mrs. Emil (Tillie Mandelbaum) Taussig',),
 ('Mrs. Guillaume Joseph (Emma) de Messemaeker',),
 ('Mr. Alfred J Davies',),
 ('Mrs. Edward Dale (Charlotte Lamson) Appleton',),
 ('Mrs. William Baird (Alice Munger) Silvey',),
 ('Mrs. Joseph (Maria Elias) Caram',),
 ('Miss. Julie Rachel Christy',),
 ('Mrs. John Borland (Marian Longstreth Morris) Thayer',),
 ('Mr. Maxmillian Frolicher-Stehli',),
 ('Mrs. Walter Bertram (Martha Eustis) Stephenson',),
 ('Mr. John Henry Chapman',),
 ('Mr. Jean Baptiste Van Impe',),
 ('Sir. Cosmo Edmund Duff Gordon',),
 ('Mrs. Sidney Samuel (Amy Frances Christy) Jacobsohn',),
 ('Mr. Edvard Bengtsson Lindell',),
 ('Mrs. Joseph (Juliette Marie Louise Lafargue) Laroche',),
 ('Mrs. Anders Johan (Alfrida Konstantia Brogren) Andersson',),
 ('Miss. Margaret Jane Murphy',),
 ('Miss. Alice Herman',),
 ('Mr. Ernst Gilbert Danbom',),
 ('Mrs. William Arthur (Cordelia K Stanlick) Lobb',),
 ('Miss. Marion Louise Becker',),
 ('Mr. Antoni Yasbeck',),
 ('Mr. Edwin Nelson Jr Kimball',),
 ('Mr. Sahid Nakid',),
 ('Miss. Mabel Skoog',),
 ('Mr. Harvey Collyer',),
 ('Mr. Percival Thorneycroft',),
 ('Miss. Margit Elizabeth Skoog',),
 ('Miss. Eugenie Baclini',),
 ('Mr. Henry Sleeper Harper',),
 ('Mr. Leonard Mark Hickman',),
 ('Mrs. John (Catherine) Bourke',),
 ('Dr. Henry William Frauenthal',),
 ('Mr. Eino William Lindqvist',),
 ('Mr. Lewis Hickman',),
 ('Mrs. Elmer Zebley (Juliet Cummins Wright) Taylor',),
 ('Mrs. Thomas William Solomon (Elizabeth Catherine Ford) Brown',),
 ('Mr. Thornton Davidson',),
 ('Mrs. Frederick (Augusta Tyler) Goodwin',),
 ('Mr. Charles Edward Goodwin',),
 ('Mr. Thomas William Solomon Brown',),
 ('Mr. Joseph Philippe Lemercier Laroche',),
 ('Mr. Jaako Arnold Panula',),
 ('Mr. Albert Adrian Dick',),
 ('Mr. John Borland Thayer',),
 ('Mrs. John Jacob (Madeleine Talmadge Force) Astor',),
 ('Mr. Henrik Juul Hansen',),
 ('Master. Halim Gonios Moubarek',),
 ('Mr. Elmer Zebley Taylor',),
 ('Mr. Svend Lauritz Jensen',),
 ('Mr. Norman Campbell Chambers',),
 ('Mrs. Peter Henry (Lillian Jefferys) Renouf',),
 ('Mr. Kurt Arnold Gottfrid Bryhl',),
 ('Miss. Pieta Sofia Ilmakangas',),
 ('Mrs. Edward (Margaret Ann Watson) Ford',),
 ('Mr. Tyrell William Cavendish',),
 ('Miss. Susan Parker Ryerson',),
 ('Mr. Neal McNamee',),
 ('Capt. Edward Gifford Crosby',),
 ('Mr. Rossmore Edward Abbott',),
 ('Mr. Daniel Warner Marvin',),
 ('Miss. Joan Wells',),
 ('Mrs. Samuel (Jane Laver) Herman',),
 ('Master. Viljo Hamalainen',),
 ('Mrs. William Ernest (Lucile Polk) Carter',),
 ('Mrs. John C (Anna Andrews) Hogeboom',),
 ('Mr. Daniel J Moran',),
 ('Mrs. Elizabeth (Eliza Needs) Hocking',),
 ('Mrs. Albert Adrian (Vera Gillespie) Dick',),
 ('Mr. Andrew G Johnston',),
 ('Master. George Hugh Rice',),
 ('Master. Bertram Vere Dean',),
 ('Miss. Stella Anna Sage',),
 ('Mrs. Jean Baptiste (Rosalie Paula Govaert) Van Impe',),
 ('Mrs. Harvey (Charlotte Annie Tate) Collyer',),
 ('Master. William Thornton II Carter',),
 ('Mrs. Norman Campbell (Bertha Griggs) Chambers',),
 ('Miss. Ebba Iris Alfrida Andersson',),
 ('Mr. Albert Mallet',),
 ('Master. Karl Thorsten Skoog',),
 ('Mrs. Charles Melville (Clara Jennings Gregg) Hays',),
 ('Master. Urho Abraham Panula',),
 ('Mrs. Antoni (Selini Alexander) Yasbeck',),
 ('Master. George Sibley Richards',),
 ('Miss. Sara Rebecca Compton',),
 ('Mr. Douglas Bullen Sage',),
 ('Mrs. Samuel L (Edwiga Grabowska) Goldenberg',),
 ('Master. Sigvard Harald Elias Andersson',),
 ('Miss. Nourelain Boulos',),
 ('Mrs. Ernest Courtenay (Lilian Hughes) Carter',),
 ('Mrs. George Dennick (Mary Hitchcock) Wick',),
 ('Mr. Claus Peter Hansen',),
 ('Mr. Frederick Edward Giles',),
 ('Miss. Dorothy Edith Sage',),
 ('Miss. Asuncion Duran y More',),
 ('Master. Harold Theodor Johnson',),
 ('Mrs. Richard Leonard (Sallie Monypeny) Beckwith',),
 ('Mrs. Samuel (Hannah Wizosky) Abelson',),
 ('Miss. Catherine Helen Johnston',)]

In [83]:
all_names = [x[0] for x in names]
names_we_care_about = [(x.split()[0], x.split()[-1]) for x in all_names if x.split()[0] in ['Mr.', 'Mrs.']]
found_names = {}
married_count = 0
for prefix, name in names_we_care_about:
    if name in found_names:
        
        if found_names[name] != prefix:
            married_count += 1
    else:
        found_names[name] = prefix
print("number of married couples: ", married_count)

number of married couples:  49

In [65]:
pg_conn.close()
pg_conn = psycopg2.connect(
    database=database, user=user, password=password, host=host)
pg_cur = pg_conn.cursor()

In [82]:
pg_conn.close()